Run linter in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,10 +40,50 @@ jobs:
                     ./LinuxX11
                     ./Windows Desktop
 
+    linter:
+        name: GDLint Check
+        runs-on: ubuntu-latest
+
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4
+
+            - name: Load Python Cache
+              id: cache-python
+              uses: actions/cache@v2
+              with:
+                path: ./.venv/
+                key: ${{ runner.os }}-python-${{ hashFiles('**/linter_requirements.txt') }}
+
+            - name: Build Python venv
+              run: |
+                python -m venv ./.venv
+                source ./.venv/bin/activate
+                pip install -r linter_requirements.txt
+              if: steps.cache-python.outputs.cache-hit != 'true'
+
+            - name: Lint
+              run: |
+                source ./.venv/bin/activate
+                gdlint . > lint_report.txt
+
+            - name: Upload Lint Report
+              uses: actions/upload-artifact@v4
+              with:
+                  name: lint_report
+                  path: lint_report.txt
+
+            - name: Check Lint Report
+              run: |
+                if grep -q "Error" lint_report.txt; then
+                    echo "Lint failed"
+                    exit 1
+                fi
+
     upload_release:
         name: Upload Release
         runs-on: ubuntu-latest
-        needs: build
+        needs: [build, linter]
         if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
 
         steps:
@@ -51,7 +91,7 @@ jobs:
               uses: actions/download-artifact@v4
               with:
                 name: build_game
-            
+
             - name: Create Release
               uses: softprops/action-gh-release@v2
               with:
